<?php
/**
 * Copyright © Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Paazl\CheckoutWidget\Block\Checkout\Widget as CheckoutWidgetBlock;

/** @var CheckoutWidgetBlock $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<?php
$scriptString = '';

if ($block->getApiBaseUrl()) {
    $scriptString .= sprintf("window.PAAZL_CHECKOUT_WIDGET_API_URL = '%s';\n", $block->escapeJs($block->getApiBaseUrl()));
    $scriptString .= sprintf("window.PAAZL_CHECKOUT_WIDGET_LOCAL_RESOURCE_URL = '%s';\n", $block->escapeJs($block->getLocalResourceUrl()));
}

if ($block->useLocal()) {
    $scriptString .= sprintf("window.PAAZL_CHECKOUT_WIDGET_RESOURCE_URL = '%s';\n", $block->escapeJs($block->getLocalResourceUrl()));
}
?>
<?php if (isset($secureRenderer)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else: ?>
    <?= /* @noEscape */ sprintf('<script type="text/javascript">%s</script>', $scriptString) ?>
<?php endif; ?>

<?php if ($block->getCustomCss() != '') : ?>
    <?php $styleString = sprintf(':root {%s}', $block->getCustomCss()); ?>
    <?php if (isset($secureRenderer)): ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styleString, false) ?>
    <?php else: ?>
        <style><?= /* @noEscape */ $styleString ?></style>
    <?php endif; ?>
<?php endif; ?>
