<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Backend\Block\Template;

/** @var Template $block */
/** @var SecureHtmlRenderer $secureRenderer */

$scriptString = "
    require([
        'jquery',
        'Magento_Sales/order/create/scripts',
        'Paazl_CheckoutWidget/js/admin/order/create/shipping/method/paazl/widget/modal',
        'jquery/ui'
    ], function ($) {
        'use strict';

        AdminOrder.prototype.showModalFlag = true;
        AdminOrder.prototype.oldShippingMethod = null;
        AdminOrder.prototype.shippingMethod = null;


        AdminOrder.prototype.setShippingMethod = AdminOrder.prototype.setShippingMethod.wrap(
            function (parentFunction, method) {
                this.oldShippingMethod = this.shippingMethod;

                if (this.showModalFlag && method === 'paazlshipping_paazlshipping') {
                    jQuery('#paazl-modal').paazlWidgetModal('openModal');

                    return false;
                }

                this.showModalFlag = true;
                parentFunction(method);
                this.shippingMethod = method;
            }
        );
    });
";

?>
<?php if (class_exists(SecureHtmlRenderer::class)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else: ?>
    <?= /* @noEscape */ sprintf('<script type="text/javascript">%s</script>', $scriptString) ?>
<?php endif; ?>
