<?php
/**
 * Copyright © 2019 Paazl. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Paazl\CheckoutWidget\Block\Adminhtml\Order\Create\Shipping\Method\Paazl\Widget\Config as WidgetConfig;

/** @var WidgetConfig $block */
/** @var SecureHtmlRenderer $secureRenderer */

$scriptString = "
    require(
        ['Magento_Sales/order/create/form'],
        function () {
            Object.assign(order, {$block->getSerializedWidgetConfig()});
        }
    );
";

?>
<?php if (class_exists(SecureHtmlRenderer::class)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else: ?>
    <?= /* @noEscape */ sprintf('<script>%s</script>', $scriptString) ?>
<?php endif; ?>
